version: '3.7'
services:
  redis:
    image: redis:alpine
    container_name: ${CONTAINER_PREFIX}_redis
    ports:
      - ${REDIS_EXT_PORT}:6379
  pgsql:
    image: postgres:alpine
    container_name: ${CONTAINER_PREFIX}_pgsql
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - ${PGSQL_EXT_PORT}:5432
    volumes:
      - data:/var/lib/postgresql/data
  mongo:
    image: mongo
    container_name: ${CONTAINER_PREFIX}_mongo
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    ports:
      - ${MONGO_EXT_PORT}:27017
    volumes:
      - data:/data/db
  nginx:
    container_name: ${CONTAINER_PREFIX}_nginx
    build:
      context: ./nginx
    volumes:
      - ${PATH_PROJECT_HOST}:${PATH_PROJECT_CONTAINER}
    ports:
      - ${NGINX_EXT_PORT}:80
  php:
    container_name: ${CONTAINER_PREFIX}_php
    build:
      context: ./php
    volumes:
      - ${PATH_PROJECT_HOST}:${PATH_PROJECT_CONTAINER}
    environment:
      XDEBUG_CONFIG: remote_host=${XDEBUG_REMOTE_HOST}
      PHP_IDE_CONFIG: serverName=${CONTAINER_PREFIX}
  workplace:
    container_name: ${CONTAINER_PREFIX}_workplace
    build:
      context: ./workplace
      args:
        - PATH_PROJECT_CONTAINER=${PATH_PROJECT_CONTAINER}
    volumes:
      - ${PATH_PROJECT_HOST}:${PATH_PROJECT_CONTAINER}
volumes:
  data:
    external: true
    name: ${CONTAINER_PREFIX}_data
